name: Theme deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Upload theme
        env:
          SHOPIFY_FLAG_FORCE: 1
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        run: |
          shopify theme push \
            --json \
            --theme 132674551923 \
            --store ${{ SHOPIFY_FLAG_STORE }} \
            --password ${{ SHOPIFY_CLI_THEME_TOKEN }} \
            --allow-live