name: Theme Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # Debug file diff
      - name: Debug File Diff
        run: |
          echo "Changed files:"
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }}

      # Debug theme check config
      - name: Debug Theme Check Config
        run: |
          echo "Looking for .theme-check.yml"
          find . -name ".theme-check.yml" || echo "No config file found"

      - name: Run Theme Check on Shopify theme
        uses: Shopify/theme-check-action@v2.1.2
        with:
          theme_root: '.'
          token: ${{ github.token }}
          base: ${{ github.event.pull_request.base.sha }}
          flags: '--output json'  # Thêm flag để force JSON output

      - name: Show Theme Check Results
        if: always()
        run: |
          echo "Theme Check CLI version:"
          theme check --version || echo "Theme check not found"
          
          echo "Checking results file:"
          if [ -f /tmp/results.json ]; then
            echo "Results found:"
            cat /tmp/results.json | jq '.'
          else
            echo "No results file found"
            ls -la /tmp/
          fi