name: Theme Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions: write-all

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Theme Check
        id: theme-check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: '.'
          token: ${{ github.token }}
          base: main
          flags: '--fail-level error --output json'

      - name: Print Theme Check Results
        run: |
          echo "Theme Check Output:"
          shopify theme check --output json

      - name: Comment PR on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `## Theme Check Results ❌

            Theme check found some issues that need to be addressed:
            
            \`\`\`
            ${process.env.THEME_CHECK_OUTPUT || 'Details in the Checks tab of the PR'}
            \`\`\`

            Please check and fix the issues before merging.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            }) 