name: Theme Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Fetch Git History
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}
          git fetch origin ${{ github.sha }}

      - name: Theme Check
        id: theme-check
        uses: shopify/theme-check-action@v2
        env:
          DEBUG: 'theme-check:*'  # Enable debug logging
        with:
          theme_root: '.'
          token: ${{ github.token }}
          base: ${{ github.event.pull_request.base.sha }}

      # Debug output sau khi chạy Theme Check
      - name: Debug Theme Check Output
        if: always()
        run: |
          echo "Action outputs:"
          echo "Exit code: ${{ steps.theme-check.outputs.exit_code || 'not set' }}"
          echo "Has errors: ${{ steps.theme-check.outputs.has_errors || 'not set' }}"
          
          echo "Looking for results in different locations:"
          find . -name "results.json" -type f
          find /tmp -name "results.json" -type f
          
          echo "GitHub context:"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.sha }}"