name: Theme Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions: write-all  

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write 
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: '.'
          token: ${{ github.token }}
          base: main
          flags: '--fail-level error'

      - name: Process Theme Check Results
        if: always()
        run: |
          if [ -f /tmp/results.json ]; then
            echo "Theme Check Results:"
            cat /tmp/results.json | jq -r '.[] | select(.severity == "error") | "Error in \(.path): \(.message)"'
            
            ERROR_COUNT=$(cat /tmp/results.json | jq '[.[] | select(.severity == "error")] | length')
            if [ $ERROR_COUNT -gt 0 ]; then
              echo "Found $ERROR_COUNT errors in theme check"
              exit 1
            else
              echo "No errors found in theme check"
            fi
          else
            echo "No results file found - no theme files were likely checked"
            exit 0
          fi 