name: Theme Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # Fetch đầy đủ
      - name: Fetch all history
        run: |
          git fetch --prune
          git fetch origin main
          git fetch origin ${{ github.head_ref }}

      # Lấy changed files
      - name: Get changed files
        id: changed-files
        run: |
          echo "Checking changes between ${{ github.event.pull_request.base.sha }} and ${{ github.event.pull_request.head.sha }}"
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep -E '\.liquid$|\.js$|\.css$|\.scss$|\.json$' || true)
          echo "Changed theme files:"
          echo "$CHANGED_FILES"
          echo "files=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Theme Check
        uses: shopify/theme-check-action@v2
        env:
          THEME_CHECK_OPTIONS: "--fail-level error"
        with:
          theme_root: '.'
          token: ${{ github.token }}
          base: ${{ github.event.pull_request.base.sha }}

      - name: Process Results
        if: always()
        run: |
          if [ -f /tmp/results.json ]; then
            echo "Processing theme check results..."
            
            # Convert results to GitHub annotations format
            jq -r '.[] | select(.severity == "error") | 
              "::error file=\(.path),line=\(.start_row)::[\(.check_name)] \(.message)"' /tmp/results.json || true
            
            # Check for errors
            ERROR_COUNT=$(jq '[.[] | select(.severity == "error")] | length' /tmp/results.json)
            if [ "$ERROR_COUNT" -gt 0 ]; then
              echo "Found $ERROR_COUNT errors"
              exit 1
            fi
          else
            echo "No results file found - checking if any theme files were changed"
            if [ -n "${{ steps.changed-files.outputs.files }}" ]; then
              echo "Theme files were changed but no results found"
              exit 1
            else
              echo "No theme files were changed"
            fi
          fi