name: Theme Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions: write-all  

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write 
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # Add custom error handling script
      - name: Create error handler
        run: |
          echo '#!/bin/bash
          output=$(theme-check $@ 2>&1)
          code=$?
          if echo "$output" | grep -q "No theme files found."; then
            echo "No theme files found, proceeding without error."
            exit 0
          fi
          echo "$output"
          exit $code' > theme-check-wrapper.sh
          chmod +x theme-check-wrapper.sh

      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: '.'
          token: ${{ github.token }}
          base: main
          flags: '--fail-level error --print' 