name: Theme Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.liquid'
      - '**.json'
      - '**.js'
      - '**.scss'

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: '.'
          token: ${{ github.token }}
          base: main
          flags: '--fail-level error' 