name: Theme Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions: write-all

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Theme Check
        id: theme-check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: '.'
          token: ${{ github.token }}
          base: main
          flags: '--fail-level error'
        continue-on-error: true

      - name: Comment PR with Results
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = '${{ steps.theme-check.outcome }}';
            const checkOutput = `${{ steps.theme-check.outputs.check_output }}`;
            const emoji = status === 'success' ? '✅' : '❌';
            
            const output = `## Theme Check Results ${emoji}
            
            ${status === 'success' 
              ? '✨ Great! No issues found.' 
              : `### List of issues to fix:
              
            \`\`\`
            ${checkOutput}
            \`\`\`
            
            Please fix these issues before merging.`}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            }) 