name: Theme Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # Fetch thêm thông tin
      - name: Fetch Git History
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}
          git fetch origin ${{ github.sha }}

      # Debug file diff
      - name: Debug File Diff
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.sha }}"
          echo "Changed files:"
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }}

      - name: Theme Check
        uses: Shopify/theme-check-action@v2.1.2
        with:
          theme_root: '.'
          token: ${{ github.token }}
          base: ${{ github.event.pull_request.base.sha }}
          flags: '--output json'

      - name: Show Theme Check Results
        if: always()
        run: |
          echo "Theme Check output location:"
          pwd
          echo "Temporary directory contents:"
          ls -la /tmp/
          
          if [ -f /tmp/results.json ]; then
            echo "Results found:"
            cat /tmp/results.json | jq '.'
          else
            echo "Looking for results file in current directory:"
            find . -name "results.json"
          fi